// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZa0TFyCUggPY5p2O7tMQvarvPsaljAoE',
    appId: '1:991945889722:web:0e710398a35672282f2f83',
    messagingSenderId: '991945889722',
    projectId: 'fir-flutter-codelab-ef42b',
    authDomain: 'fir-flutter-codelab-ef42b.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ef42b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIaJuaxspvQFoIHWcu2F57vovBtSfnkjM',
    appId: '1:991945889722:android:0fc190c5722ae4802f2f83',
    messagingSenderId: '991945889722',
    projectId: 'fir-flutter-codelab-ef42b',
    storageBucket: 'fir-flutter-codelab-ef42b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8q10qIXbaqIvbkLO0geLvB1bnydyBD8Y',
    appId: '1:991945889722:ios:28ba5b379f43f3352f2f83',
    messagingSenderId: '991945889722',
    projectId: 'fir-flutter-codelab-ef42b',
    storageBucket: 'fir-flutter-codelab-ef42b.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8q10qIXbaqIvbkLO0geLvB1bnydyBD8Y',
    appId: '1:991945889722:ios:28ba5b379f43f3352f2f83',
    messagingSenderId: '991945889722',
    projectId: 'fir-flutter-codelab-ef42b',
    storageBucket: 'fir-flutter-codelab-ef42b.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZa0TFyCUggPY5p2O7tMQvarvPsaljAoE',
    appId: '1:991945889722:web:8f8ca3e7d725934b2f2f83',
    messagingSenderId: '991945889722',
    projectId: 'fir-flutter-codelab-ef42b',
    authDomain: 'fir-flutter-codelab-ef42b.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ef42b.appspot.com',
  );
}
